---
- name: Instalar auditd
  apt:
    name:
      - auditd
      - audispd-plugins
    state: present
    update_cache: true

- name: Asegurar que auditd está habilitado
  systemd:
    name: auditd
    enabled: true
    state: started

# ----------------------------
# CONFIGURACIÓN DE AUDITD
# ----------------------------

- name: Configurar auditd.conf
  copy:
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: "0640"
    content: |
      log_file = /var/log/audit/audit.log
      log_format = RAW
      flush = INCREMENTAL
      freq = 50

      max_log_file = {{ auditd_max_log_file | default(50) }}
      num_logs = {{ auditd_num_logs | default(10) }}

      max_log_file_action = ROTATE
      space_left = {{ auditd_space_left | default(75) }}
      space_left_action = SYSLOG
      admin_space_left_action = SUSPEND
      disk_full_action = SUSPEND
      disk_error_action = SUSPEND

      name_format = hostname
    backup: true

# ----------------------------
# REGLAS DE AUDITORÍA
# ----------------------------

- name: Crear reglas de auditoría
  copy:
    dest: /etc/audit/rules.d/ccn.rules
    owner: root
    group: root
    mode: "0640"
    content: |
      ## BORRAR REGLAS EXISTENTES
      -D

      ## BUFFER
      -b 8192

      ## FALLOS CRÍTICOS
      -f 1

      ## AUDITAR CAMBIOS EN IDENTIDAD
      -w /etc/passwd -p wa -k identity
      -w /etc/shadow -p wa -k identity
      -w /etc/group -p wa -k identity
      -w /etc/gshadow -p wa -k identity

      ## AUDITAR SUDO Y PAM
      -w /etc/sudoers -p wa -k scope
      -w /etc/sudoers.d -p wa -k scope
      -w /etc/pam.d -p wa -k auth

      ## AUDITAR EJECUCIÓN COMO ROOT
      -a always,exit -F arch=b64 -F euid=0 -S execve -k privileged

      ## AUDITAR LOGIN
      -w /var/log/faillog -p wa -k logins
      -w /var/log/lastlog -p wa -k logins
      -w /var/log/tallylog -p wa -k logins

      ## AUDITAR CRON
      -w /etc/cron.allow -p wa -k cron
      -w /etc/cron.deny -p wa -k cron
      -w /etc/cron.d -p wa -k cron
      -w /etc/crontab -p wa -k cron

      ## AUDITAR RED
      -w /etc/hosts -p wa -k network
      -w /etc/resolv.conf -p wa -k network

      ## AUDITAR DISPOSITIVOS
      -w /media -p wa -k devices
      -w /run/media -p wa -k devices

      ## FIN
      -e 2
    backup: true

# ----------------------------
# CARGA DE REGLAS
# ----------------------------

- name: Cargar reglas de auditoría
  command: augenrules --load
  register: augenrules_result
  changed_when: "'No change' not in augenrules_result.stdout"
  failed_when: >
    augenrules_result.rc != 0 and
    'No change' not in augenrules_result.stdout
  notify: restart auditd

# ----------------------------
# VALIDACIÓN
# ----------------------------

- name: Comprobar estado de auditd
  command: auditctl -s
  register: auditd_status
  changed_when: false